#!/usr/bin/env python3
"""Build reproducible clean-study and restoration metrics for the CCI paper."""

from __future__ import annotations

import argparse
import csv
import json
import statistics
from pathlib import Path
from typing import Iterable


VARIANTS = ("A0", "A10", "A11")
PREFIXES = {"A0": "RawBLD", "A10": "FixedCCI", "A11": "AdaptiveCCI"}


def _truth(value: str) -> bool:
    if value == "True":
        return True
    if value == "False":
        return False
    raise ValueError(f"invalid boolean value: {value!r}")


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"empty cohort: {path}")
    return rows


def _mean(rows: Iterable[dict[str, str]], field: str) -> float:
    return statistics.fmean(float(row[field]) for row in rows)


def build_metrics(
    cohort_paths: list[Path],
    expected_per_cohort: int,
    ablation_path: Path,
) -> dict[str, object]:
    """Validate paired cohorts and aggregate the paper's completed evidence."""
    if not cohort_paths:
        raise ValueError("at least one cohort is required")
    if expected_per_cohort <= 0:
        raise ValueError("expected_per_cohort must be positive")

    all_rows: list[dict[str, str]] = []
    seen_cohort_ids: set[int] = set()
    cohort_records: list[dict[str, object]] = []
    for path in cohort_paths:
        rows = _read_rows(path)
        ids_by_variant = {
            variant: {
                int(row["sample_id"])
                for row in rows
                if row["variant"] == variant
            }
            for variant in VARIANTS
        }
        if any(
            len(ids) != expected_per_cohort for ids in ids_by_variant.values()
        ):
            raise ValueError(f"unexpected paired count in {path}: {ids_by_variant}")
        if not (
            ids_by_variant["A0"]
            == ids_by_variant["A10"]
            == ids_by_variant["A11"]
        ):
            raise ValueError(f"variants are not paired in {path}")
        cohort_ids = ids_by_variant["A0"]
        overlap = seen_cohort_ids & cohort_ids
        if overlap:
            raise ValueError(f"cohorts are not disjoint: {sorted(overlap)}")
        seen_cohort_ids.update(cohort_ids)
        cohort_records.append({"path": str(path), "source_count": len(cohort_ids)})
        all_rows.extend(rows)

    methods: dict[str, object] = {}
    for variant in VARIANTS:
        rows = [row for row in all_rows if row["variant"] == variant]
        methods[variant] = {
            "count": len(rows),
            "target_pass_rate": statistics.fmean(
                _truth(row["target_pass"]) for row in rows
            ),
            "mean_identity_cosine": _mean(rows, "identity_cosine"),
            "mean_strict_outside_mae": _mean(rows, "strict_outside_mae"),
            "mean_non_target_drift": _mean(rows, "non_target_drift"),
            "median_runtime_seconds": statistics.median(
                float(row["runtime_seconds"]) for row in rows
            ),
        }

    ablation = json.loads(ablation_path.read_text(encoding="utf-8"))
    restoration = {
        "sample_id": int(ablation["sample_id"]),
        "before": ablation["before"],
        "after": ablation["after"],
        "pixel": ablation["pixel"],
        "accepted_steps": int(ablation["restoration"]["accepted_steps"]),
    }
    return {
        "cohort": {
            "cohorts": cohort_records,
            "unique_sources": len(seen_cohort_ids),
            "post_attack": False,
        },
        "methods": methods,
        "restoration": restoration,
    }


def write_tex(payload: dict[str, object], path: Path) -> None:
    """Write stable LaTeX commands for completed aggregate metrics."""
    lines = ["% Generated by scripts/build_cci_paper_metrics.py; do not edit."]
    methods = payload["methods"]
    for variant in VARIANTS:
        values = methods[variant]
        prefix = PREFIXES[variant]
        commands = {
            "SampleCount": f'{values["count"]}',
            "TargetPassRatePct": f'{100 * values["target_pass_rate"]:.1f}',
            "IdentityCosine": f'{values["mean_identity_cosine"]:.4f}',
            "OutsideMAE": f'{values["mean_strict_outside_mae"]:.3f}',
            "NonTargetDrift": f'{values["mean_non_target_drift"]:.4f}',
            "RuntimeMedian": f'{values["median_runtime_seconds"]:.1f}',
        }
        lines.extend(
            f"\\newcommand{{\\{prefix}{name}}}{{{value}}}"
            for name, value in commands.items()
        )
    fixed_drift = methods["A10"]["mean_non_target_drift"]
    adaptive_drift = methods["A11"]["mean_non_target_drift"]
    reduction = 100.0 * (fixed_drift - adaptive_drift) / fixed_drift
    lines.append(
        "\\newcommand{\\AdaptiveDriftReductionVsFixedPct}"
        f"{{{reduction:.1f}}}"
    )
    restoration = payload["restoration"]
    before = restoration["before"]
    after = restoration["after"]
    pixel = restoration["pixel"]
    restoration_commands = {
        "RestorationSampleID": f'{restoration["sample_id"]}',
        "RestorationBeforeProbability": f'{before["desired_probability"]:.4f}',
        "RestorationAfterProbability": f'{after["desired_probability"]:.4f}',
        "RestorationBeforeIdentity": f'{before["identity_cosine"]:.4f}',
        "RestorationAfterIdentity": f'{after["identity_cosine"]:.4f}',
        "RestorationBeforeDrift": f'{before["mean_non_target_drift"]:.4f}',
        "RestorationAfterDrift": f'{after["mean_non_target_drift"]:.4f}',
        "RestorationBeforeRuntime": f'{before["wall_seconds"]:.1f}',
        "RestorationAfterRuntime": f'{after["wall_seconds"]:.1f}',
        "RestorationPixelMAE": f'{pixel["mean_absolute_difference"]:.6f}',
        "RestorationPixelMax": f'{pixel["maximum_absolute_difference"]:.4f}',
        "RestorationChangedPct": f'{100 * pixel["changed_fraction"]:.2f}',
        "RestorationAcceptedSteps": f'{restoration["accepted_steps"]}',
    }
    lines.extend(
        f"\\newcommand{{\\{name}}}{{{value}}}"
        for name, value in restoration_commands.items()
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cohort", action="append", type=Path, required=True)
    parser.add_argument("--expected_per_cohort", type=int, default=100)
    parser.add_argument("--ablation", type=Path, required=True)
    parser.add_argument("--json_out", type=Path, required=True)
    parser.add_argument("--tex_out", type=Path, required=True)
    args = parser.parse_args()
    payload = build_metrics(args.cohort, args.expected_per_cohort, args.ablation)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )
    write_tex(payload, args.tex_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
